version: "3"
services:
    react:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        stdin_open: true
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: ["npm", "run", "test"]